/**
 * doc-generator.ts
 * Generates machine-readable OpenAPI spec and A2A Agent Card from a CapabilityMap.
 * WHY: Agents need machine-readable docs to discover and use bridges programmatically.
 * Human-written docs alone aren't enough — the spec IS the documentation.
 */

import * as fs from 'fs';
import * as path from 'path';
import { CapabilityMap, Capability, Parameter } from '../inferrer/capability-map.js';

function paramToOpenAPISchema(param: Parameter): Record<string, unknown> {
  const base: Record<string, unknown> = {
    description: param.description,
  };

  if (param.enum && param.enum.length > 0) {
    return { ...base, type: 'string', enum: param.enum };
  }

  switch (param.type) {
    case 'number':
      return { ...base, type: 'number' };
    case 'boolean':
      return { ...base, type: 'boolean' };
    case 'array':
      return { ...base, type: 'array', items: { type: 'string' } };
    case 'object':
      return { ...base, type: 'object', additionalProperties: true };
    default:
      return { ...base, type: 'string' };
  }
}

function capabilityToOpenAPIPath(cap: Capability): Record<string, unknown> {
  const required = cap.parameters.filter((p) => p.required).map((p) => p.name);
  const properties: Record<string, unknown> = {};

  for (const param of cap.parameters) {
    properties[param.name] = paramToOpenAPISchema(param);
    if (param.example) {
      (properties[param.name] as Record<string, unknown>).example = param.example;
    }
  }

  return {
    post: {
      operationId: cap.id.replace(/\./g, '_'),
      summary: cap.name,
      description: `${cap.description}\n\nRisk level: **${cap.riskLevel}**\nRequires auth: ${cap.requiresAuth}`,
      tags: [cap.category],
      'x-risk-level': cap.riskLevel,
      requestBody: {
        required: cap.parameters.length > 0,
        content: {
          'application/json': {
            schema: {
              type: 'object',
              properties,
              required: required.length > 0 ? required : undefined,
            },
          },
        },
      },
      responses: {
        '200': {
          description: cap.returns.description,
          content: {
            'application/json': {
              schema: { type: cap.returns.type === 'void' ? 'object' : cap.returns.type },
            },
          },
        },
        '400': { description: 'Invalid parameters' },
        '401': { description: 'Agent not authenticated' },
        '403': { description: 'Permission denied — capability not in agent scope' },
        '429': { description: 'Rate limit exceeded' },
        '500': { description: 'Internal execution error' },
      },
      security: [{ ApiKeyAuth: [] }],
    },
  };
}

function generateOpenAPISpec(capMap: CapabilityMap): Record<string, unknown> {
  const paths: Record<string, unknown> = {};

  for (const cap of capMap.capabilities) {
    paths[`/capabilities/${cap.id.replace(/\./g, '/')}`] = capabilityToOpenAPIPath(cap);
  }

  return {
    openapi: '3.1.0',
    info: {
      title: `AgentBridge — ${capMap.targetName}`,
      description: `Agent-native interface for ${capMap.targetName}. Generated by AgentBridge from ${capMap.targetUrl}.`,
      version: '1.0.0',
      'x-agentbridge-version': '0.1.0',
      'x-target-url': capMap.targetUrl,
      'x-generated-at': capMap.generatedAt,
      'x-capabilities-count': capMap.capabilities.length,
    },
    servers: [{ url: `https://bridge.agentbridge.com/${capMap.bridgeId}`, description: 'AgentBridge proxy' }],
    components: {
      securitySchemes: {
        ApiKeyAuth: {
          type: 'apiKey',
          in: 'header',
          name: 'X-AgentBridge-Key',
          description: 'Register at POST /auth/register to get your API key',
        },
      },
    },
    tags: capMap.categories.map((cat) => ({
      name: cat,
      description: `${capMap.targetName} ${cat} capabilities`,
    })),
    paths,
  };
}

function generateAgentCard(capMap: CapabilityMap): Record<string, unknown> {
  // A2A-compatible Agent Card
  return {
    name: `AgentBridge/${capMap.bridgeId}`,
    description: `Agent-native interface for ${capMap.targetName}. Access ${capMap.capabilities.length} capabilities via MCP.`,
    url: `https://bridge.agentbridge.com/${capMap.bridgeId}`,
    provider: { organization: 'AgentBridge', url: 'https://agentbridge.com' },
    version: '1.0.0',
    capabilities: {
      streaming: false,
      pushNotifications: false,
      stateTransitionHistory: true,
    },
    defaultInputModes: ['application/json'],
    defaultOutputModes: ['application/json'],
    skills: capMap.capabilities.map((cap) => ({
      id: cap.id,
      name: cap.name,
      description: cap.description,
      tags: [cap.category, cap.riskLevel],
      examples: cap.parameters
        .filter((p) => p.example)
        .map((p) => `${p.name}: ${p.example ?? ''}`),
    })),
    authentication: {
      schemes: ['apiKey'],
      credentials: 'Register at POST /auth/register',
    },
    'x-agentbridge': true,
    'x-risk-summary': {
      safe: capMap.capabilities.filter((c) => c.riskLevel === 'safe').length,
      moderate: capMap.capabilities.filter((c) => c.riskLevel === 'moderate').length,
      destructive: capMap.capabilities.filter((c) => c.riskLevel === 'destructive').length,
    },
  };
}

/**
 * Write OpenAPI spec and A2A Agent Card to the bridge output directory.
 */
export async function generateDocs(capMap: CapabilityMap, outputDir: string): Promise<void> {
  fs.mkdirSync(outputDir, { recursive: true });

  // OpenAPI spec
  const openApiPath = path.join(outputDir, 'openapi.json');
  fs.writeFileSync(openApiPath, JSON.stringify(generateOpenAPISpec(capMap), null, 2), 'utf-8');

  // A2A Agent Card
  const agentCardPath = path.join(outputDir, 'agent-card.json');
  fs.writeFileSync(agentCardPath, JSON.stringify(generateAgentCard(capMap), null, 2), 'utf-8');
}
